repos:
  - repo: https://github.com/kaustubhbhal/duck
    rev: v1.0.0-alpha
    hooks:
      - id: generate-why-questions
        stages: [pre-commit]
      - id: append-why-answers
        stages: [prepare-commit-msg]
